In [4]:
import pandas as pd
df=pd.read_csv("C:/Users/HP/Downloads/playtennis.csv")
df.head(14)

    Day   Outlook Temperature Humidity    Wind PlayTennis
0    D1     Sunny         Hot     High    Weak         No
1    D2     Sunny         Hot     High  Strong         No
2    D3  Overcast         Hot     High    Weak        Yes
3    D4      Rain        Mild     High    Weak        Yes
4    D5      Rain        Cool   Normal    Weak        Yes
5    D6      Rain        Cool   Normal  Strong         No
6    D7  Overcast        Cool   Normal  Strong        Yes
7    D8     Sunny        Mild     High    Weak         No
8    D9     Sunny        Cool   Normal    Weak        Yes
9   D10      Rain        Mild   Normal    Weak        Yes
10  D11     Sunny        Mild   Normal  Strong        Yes
11  D12  Overcast        Mild     High  Strong        Yes
12  D13  Overcast         Hot   Normal    Weak        Yes
13  D14      Rain        Mild     High  Strong         No

In [3]:
df.shape

(14, 6)

In [6]:
df.dtypes

Day            object
Outlook        object
Temperature    object
Humidity       object
Wind           object
PlayTennis     object
dtype: object

In [16]:
# One-hot encoding for selected categorical columns
df_one_hot = pd.get_dummies(df, columns=['Outlook', 'Temperature', 'Humidity', 'Wind'], drop_first=True)

# Label encoding for the 'PlayTennis' column
label_mapping = {'No': 0, 'Yes': 1}
df_label_encoded = df.replace({'PlayTennis': label_mapping})

# Display the encoded DF
print("\nDF after One-Hot Encoding:")
print(df_one_hot)

print("\nDF after Label Encoding:")
print(df_label_encoded)

DF after One-Hot Encoding:
    Day PlayTennis  Outlook_Rain  Outlook_Sunny  Temperature_Hot  \
0    D1         No             0              1                1
1    D2         No             0              1                1
2    D3        Yes             0              0                1
3    D4        Yes             1              0                0
4    D5        Yes             1              0                0
5    D6         No             1              0                0
6    D7        Yes             0              0                0
7    D8         No             0              1                0
8    D9        Yes             0              1                0
9   D10        Yes             1              0                0
10  D11        Yes             0              1                0
11  D12        Yes             0              0                0
12  D13        Yes             0              0                1
13  D14         No             1              0                0

    Temperature_Mild  Humidity_Normal  Wind_Weak
0                  0                0          1
1                  0                0          0
2                  0                0          1
3                  1                0          1
4                  0                1          1
5                  0                1          0
6                  0                1          0
7                  1                0          1
8                  0                1          1
9                  1                1          1
10                 1                1          0
11                 1                0          0
12                 0                1          1
13                 1                0          0

DF after Label Encoding:
    Day   Outlook Temperature Humidity    Wind  PlayTennis
0    D1     Sunny         Hot     High    Weak           0
1    D2     Sunny         Hot     High  Strong           0
2    D3  Overcast         Hot     High    Weak           1
3    D4      Rain        Mild     High    Weak           1
4    D5      Rain        Cool   Normal    Weak           1
5    D6      Rain        Cool   Normal  Strong           0
6    D7  Overcast        Cool   Normal  Strong           1
7    D8     Sunny        Mild     High    Weak           0
8    D9     Sunny        Cool   Normal    Weak           1
9   D10      Rain        Mild   Normal    Weak           1
10  D11     Sunny        Mild   Normal  Strong           1
11  D12  Overcast        Mild     High  Strong           1
12  D13  Overcast         Hot   Normal    Weak           1
13  D14      Rain        Mild     High  Strong           0